#!/bin/sh
#
# Load firmware
#

case "$1" in
	start)
		/usr/bin/load_wdu_firmware.sh
		;;
	stop)
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
