#!/bin/sh
#
# Check partition table - add one if partitions are missing
#

BOARD=$(cat /etc/board)

case "$1" in
	start)
		echo "Checking partitions..."

		if [ "$BOARD" = "confidea_g4_wdu" ]
		then
			/usr/bin/partition_wdu.sh
		fi;

		;;
	stop)
		# nothing to do
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

exit $?
