#!/bin/sh
#
# Procedure to increase the priority of some RT IRQs to reduce the interrupt latency jitter.
# See http://linuxrealtime.org/index.php/Improving_the_Real-Time_Properties#Setting_up_a_Partitioned_System
#

# $1 Process name
# $2 PID number (1 for first hit of process name, 2 for second hit, etc.)
# $3 Priority
set_priority()
{
	PID=$(ps | awk "\$5 ~ \"$1\" {print \$1;}" | sed -n $2p)
	chrt -f -p $3 $PID > /dev/null 2>&1
}

start()
{
	set_priority "irq/46-g4-timer" 1 90
}

case "$1" in
	start)
		start
		;;
	stop)
		;;
	restart)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
